---

- name: Install Update CRON
  template:
    src="gnu-mirror.j2"
    dest="{{ mirror_cron_dir }}/gnu-mirror"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0700

- name: Setup CRON Schedule
  cron:
    name="GNU"
    minute="{{ gnu_mirror_cron_minute }}"
    hour="{{ gnu_mirror_cron_hour }}"
    user="{{ mirror_unix_user }}"
    state="present"
    job="{{ mirror_cron_dir }}/gnu-mirror >/dev/null 2>&1"
    disabled="{{ gnu_mirror_cron_disabled }}"

- stat:
    path="{{ mirror_timestamp_dir }}/gnu"
  register: tsfile

- name: Seed Timestamp File
  copy:
    content="0"
    dest="{{ mirror_timestamp_dir }}/gnu"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0644
  when: not tsfile.stat.exists
